import React, { useMemo } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import NftFeed from "../components/NftFeed";
import getNfts from "../service/getNfts";
import Navbar from "../components/Navbar";

export async function getStaticProps() {
  const nfts = await getNfts();

  return {
    props: { nfts },
  };
}

export default function Home(props: any) {
  
  return (
    <div>
      <Head>
        <title>20Mint Collection</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar/>
        <NftFeed nfts={props.nfts} />
      </main>
    </div>
  );
}
